/**
 * PORTFOLIO DATA
 * ==============
 *
 * Every project on the site is driven from this file.
 *
 * `status` controls how a project is labelled in the interface:
 *   - "concept" → shown with a "Concept" marker. These are Better Built's own
 *     design studies, not client work, and the site says so plainly.
 *   - "client"  → shown as delivered work. Only use this for real projects.
 *
 * TO ADD A REAL CLIENT PROJECT
 *   1. Build `components/previews/<slug>.tsx` exporting `Desktop` and `Mobile`.
 *   2. Register the slug in `components/previews/registry.ts`.
 *   3. Add an entry below with `status: "client"`.
 *   4. Optionally set `featured: true` to put it in the homepage hero.
 *
 * `featured` also decides where a project appears on the homepage, and the two
 * placements never overlap, so nothing shows up twice:
 *   - featured     → the hero showcase, which cycles through them
 *   - not featured → the "Selected work" grid below it
 *
 * Today that splits cleanly: the hero is the live client work, the grid is the
 * concept studies.
 *
 * The portfolio is deliberately short. Five well-made pieces read as a curated
 * body of work; a dozen reads as padding. When a new client project ships,
 * consider retiring a concept rather than adding to the pile.
 */

export type ProjectStatus = "concept" | "client";

export type Project = {
  slug: string;
  name: string;
  /** Short descriptor shown under the project name on cards. */
  category: string;
  /** Broad industry, shown in the card meta row and the case study header. */
  industry: string;
  status: ProjectStatus;
  /**
   * The domain shown in the browser-chrome URL bar and the card meta row.
   * Fictional for concept work; the business's real domain for client work.
   * This is a label; `liveUrl` is where links actually point, which may still
   * be a deployment URL while a domain is being pointed at it.
   */
  domain: string;
  /** Set on client work only — where "Visit live site" actually goes. */
  liveUrl?: string;
  /**
   * Real screenshots of the live site, used as the cover instead of a rendered
   * preview. Generated by `npm run capture:covers`.
   */
  cover?: { desktop: string; mobile: string };
  /** One line on the card. */
  summary: string;
  /** The design brief this project answers. */
  objective: string;
  /** What was in scope. */
  scope: string[];
  /** The decisions worth explaining on the case study. */
  decisions: { title: string; body: string }[];
  palette: { name: string; hex: string }[];
  typography: { role: string; value: string }[];
  /** Accent used for card hover treatment. */
  accent: string;
  /** Whether the preview reads better on a light or dark card. */
  cardTone: "light" | "dark";
  featured?: boolean;
};

export const projects: Project[] = [
  /* ---------------------------------------------------------------
     LIVE CLIENT WORK
     --------------------------------------------------------------- */
  {
    slug: "wavelink-surf",
    name: "Wavelink Surf",
    category: "Premium Surf Coaching",
    industry: "Sports & Recreation",
    status: "client",
    domain: "wavelinksurf.com",
    liveUrl: "https://wave-link-surf.vercel.app",
    cover: {
      desktop: "/work/wavelink-surf-desktop.webp",
      mobile: "/work/wavelink-surf-mobile.webp",
    },
    summary:
      "Private surf coaching in San Diego, sold on judgement rather than volume.",
    objective:
      "Make an hour in the water feel like a considered purchase. Surf lessons are usually sold on price and availability — this site had to place Wavelink alongside private coaching, where the instructor and the reading of the day's conditions are the product.",
    scope: [
      "Custom design",
      "Mobile-first build",
      "Lesson and pricing structure",
      "Booking entry points",
      "SEO foundations",
      "Launch",
    ],
    decisions: [
      {
        title: "A photograph carries the whole hero",
        body: "One full-bleed image of the coastline, a high-contrast serif line across it, and two actions. Nothing competes with the place itself, which is what people are actually buying.",
      },
      {
        title: "Three tiers, priced in the open",
        body: "Private, semi-private, and group are presented side by side with the ratio, the duration, and the per-surfer price on the card. Nothing is quoted on request.",
      },
      {
        title: "Coastal palette, held to three tones",
        body: "Deep teal, warm sand, and white. The restraint is what separates a coaching practice from a surf shop, and it keeps the photography the brightest thing on the page.",
      },
      {
        title: "Editorial serif against wide-tracked caps",
        body: "A high-contrast serif for the display lines, a wide-tracked sans for every label and action. The pairing reads closer to a travel magazine than a booking site.",
      },
    ],
    palette: [
      { name: "Ink", hex: "#15323A" },
      { name: "Sand", hex: "#C4B291" },
      { name: "Paper", hex: "#FFFFFF" },
    ],
    typography: [
      { role: "Display", value: "High-contrast serif" },
      { role: "Interface", value: "Grotesque, wide tracking" },
    ],
    accent: "#8a7038",
    cardTone: "light",
    featured: true,
  },
  {
    slug: "the-shanty",
    name: "The Shanty",
    category: "Cardiff-by-the-Sea Dive Bar",
    industry: "Bar & Nightlife",
    status: "client",
    domain: "theshantylounge.com",
    liveUrl: "https://shanty-chi.vercel.app",
    cover: {
      desktop: "/work/the-shanty-desktop.webp",
      mobile: "/work/the-shanty-mobile.webp",
    },
    summary:
      "A neighbourhood bar open since 1964, online without losing its character.",
    objective:
      "Put a sixty-year-old dive bar on the internet without sanding the edges off it. The risk with a place like this is a website that looks more polished than the room — so the design had to carry the same worn, unbothered confidence.",
    scope: [
      "Custom design",
      "Mobile-first build",
      "Photo gallery",
      "Directions and hours",
      "Local SEO foundations",
      "Launch",
    ],
    decisions: [
      {
        title: "The sign is the logo",
        body: "The wordmark runs at full width across the hero, underscored in red, with the establishment year boxed beneath it. It behaves like painted signage rather than a header element.",
      },
      {
        title: "Heavy condensed caps, one red",
        body: "A single compressed display face in near-black and one signal red does all the work. It is the typographic equivalent of a hand-painted board — loud, cheap to read, and completely unfussy.",
      },
      {
        title: "The bar's own photography, full width",
        body: "Wood panelling, pool tables, and the patio, shown large and warm. For a place selling atmosphere, the room has to be the argument.",
      },
      {
        title: "Answering what regulars actually ask",
        body: "Open till 2 AM, bring your own food, dog friendly, patio, pool. Short, blunt lines instead of a menu the bar doesn't have.",
      },
    ],
    palette: [
      { name: "Cream", hex: "#FAF7F1" },
      { name: "Ink", hex: "#1A1512" },
      { name: "Signal Red", hex: "#CF3126" },
    ],
    typography: [
      { role: "Display", value: "Heavy condensed, uppercase" },
      { role: "Body", value: "Geometric sans" },
    ],
    accent: "#cf3126",
    cardTone: "dark",
    featured: true,
  },

  /* ---------------------------------------------------------------
     CONCEPT STUDIES — Better Built's own design work, not client
     engagements. The businesses below are fictional.
     --------------------------------------------------------------- */
  {
    slug: "sable-and-oak",
    name: "Sable & Oak",
    category: "Chophouse & Wine Cellar",
    industry: "Restaurant",
    status: "concept",
    domain: "sableandoak.example",
    summary:
      "A dinner-only chophouse that needed a site as considered as its room.",
    objective:
      "Make a reservation feel like an occasion. The site had to carry the low light and ceremony of the dining room without burying the two things guests actually come for: the menu and a table.",
    scope: [
      "Custom design",
      "Mobile-first build",
      "Menu architecture",
      "Reservation flow",
      "Local SEO foundations",
    ],
    decisions: [
      {
        title: "The reservation never leaves the screen",
        body: "A booking action sits in the header, in the hero, and at the end of every section. Restaurant traffic is impatient and mostly mobile — the ask should never be more than a thumb-reach away.",
      },
      {
        title: "Centred type, generous margins",
        body: "A symmetrical, centred hero borrows the formality of a printed menu. Wide margins do the work that photography usually does, so the page still feels expensive on a slow connection.",
      },
      {
        title: "Warmth from a single accent",
        body: "One brass tone against near-black carries the candlelight. Everything else is cream and shadow, which keeps the menu itself the highest-contrast element on the page.",
      },
    ],
    palette: [
      { name: "Charcoal", hex: "#14120F" },
      { name: "Cream", hex: "#F3ECE0" },
      { name: "Brass", hex: "#C08A3E" },
    ],
    typography: [
      { role: "Display", value: "High-contrast serif" },
      { role: "Interface", value: "Neutral sans, wide tracking" },
    ],
    accent: "#c08a3e",
    cardTone: "dark",
  },
  {
    slug: "ironwood-construction",
    name: "Ironwood Construction",
    category: "Commercial General Contractor",
    industry: "Construction",
    status: "concept",
    domain: "ironwoodbuilds.example",
    summary:
      "A general contractor bidding against firms five times its size.",
    objective:
      "Look like the safe choice. Owners and developers award work on perceived reliability, so the site had to project process and capacity before it projected craft.",
    scope: [
      "Custom design",
      "Mobile-first build",
      "Sector and project structure",
      "Bid request flow",
      "SEO foundations",
    ],
    decisions: [
      {
        title: "Numbered delivery methods",
        body: "Preconstruction, design-build, self-perform are numbered because they are genuinely sequential in how a project is awarded and run. The numerals are information, not decoration.",
      },
      {
        title: "A project caption that carries data",
        body: "Every project image is captioned with name and square footage. In construction, scale is the credential — it belongs on the image, not three clicks deep.",
      },
      {
        title: "Steel and amber, held tightly",
        body: "One high-visibility accent used only for actions and figures. It reads as site signage without turning the page into a hazard sign.",
      },
    ],
    palette: [
      { name: "Graphite", hex: "#101211" },
      { name: "Steel", hex: "#C9CCD1" },
      { name: "Amber", hex: "#E0A324" },
    ],
    typography: [
      { role: "Display", value: "Heavy grotesque, uppercase" },
      { role: "Data", value: "Monospace" },
    ],
    accent: "#e0a324",
    cardTone: "dark",
  },
  {
    slug: "clearwater-home-services",
    name: "Clearwater Plumbing",
    category: "Plumbing & Heating",
    industry: "Home Services",
    status: "concept",
    domain: "clearwaterplumbing.example",
    summary:
      "A home services business where every visitor is a few minutes from calling someone.",
    objective:
      "Remove friction, fast. Home services traffic arrives mid-problem on a phone, so the site had to answer trust, price, and availability before it did anything else.",
    scope: [
      "Custom design",
      "Mobile-first build",
      "Service area structure",
      "Call and quote request flows",
      "Local SEO foundations",
    ],
    decisions: [
      {
        title: "The phone number is fixed at the top",
        body: "A utility bar carries the number and the licence claim on every screen. For an emergency call-out, the fastest path to a phone call is the whole design problem.",
      },
      {
        title: "Pricing anxiety answered in the subhead",
        body: "\"Upfront pricing before we start\" addresses the objection homeowners actually have. It costs one line and removes the main reason people keep dialling competitors.",
      },
      {
        title: "Bright, plain, and legible",
        body: "Large type, high contrast, generous tap targets. This is the least decorated site in the portfolio, and deliberately so — it is built for someone standing in an inch of water.",
      },
    ],
    palette: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Deep", hex: "#12212B" },
      { name: "Blue", hex: "#1668A8" },
    ],
    typography: [
      { role: "Display", value: "Bold grotesque" },
      { role: "Body", value: "Neutral sans" },
    ],
    accent: "#1668a8",
    cardTone: "light",
  },
];

export const featuredProjects = projects.filter((p) => p.featured);

export function getProject(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

export function adjacentProjects(slug: string) {
  const index = projects.findIndex((p) => p.slug === slug);
  if (index === -1) return { previous: undefined, next: undefined };
  return {
    previous: projects[(index - 1 + projects.length) % projects.length],
    next: projects[(index + 1) % projects.length],
  };
}

/**
 * Alternative text for a project preview. The previews are pictures of
 * websites, so they need a description the way a photograph would.
 */
export function previewLabel(project: Project, device: "desktop" | "mobile") {
  const kind = project.status === "concept" ? "Concept website design" : "Website";
  return `${kind} for ${project.name}, ${project.category} — ${device} view`;
}
