/**
 * Finds the horizontal section boundaries of the two page screenshots so the
 * transition can be cut along the pages' real structure rather than an
 * arbitrary grid.
 *
 * Scaling each image to a single pixel wide gives the mean luminance of every
 * row. Large jumps between adjacent rows are where one section stops and the
 * next begins — a header ending, a hero meeting a feature strip, a dark band
 * meeting a light one.
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";

const BANDS = 7;
const MIN_GAP = 0.055; // no two boundaries closer than 5.5% of page height

function rowLuminance(file) {
  const raw = execFileSync(
    "ffmpeg",
    ["-v", "error", "-i", file, "-vf", "scale=1:512,format=gray", "-f", "rawvideo", "-"],
    { maxBuffer: 1 << 22 },
  );
  return Array.from(raw);
}

/** Boundary strength at each row, smoothed so texture doesn't register as structure. */
function edgeProfile(rows) {
  const d = rows.map((v, i) => (i === 0 ? 0 : Math.abs(v - rows[i - 1])));
  return d.map((_, i) => {
    let sum = 0;
    for (let k = -2; k <= 2; k++) sum += d[Math.min(d.length - 1, Math.max(0, i + k))];
    return sum / 5;
  });
}

const profiles = ["old.jpg", "new.jpg"].map((f) => {
  const p = edgeProfile(rowLuminance(f));
  const max = Math.max(...p) || 1;
  return p.map((v) => v / max);
});

// Both pages describe the same business, so their structures reinforce each other.
const combined = profiles[0].map((v, i) => v + profiles[1][i]);

const candidates = combined
  .map((strength, i) => ({ y: i / (combined.length - 1), strength }))
  .filter((c) => c.y > 0.06 && c.y < 0.94)
  .sort((a, b) => b.strength - a.strength);

const picked = [];
for (const c of candidates) {
  if (picked.length >= BANDS - 1) break;
  if (picked.every((p) => Math.abs(p - c.y) >= MIN_GAP)) picked.push(c.y);
}
picked.sort((a, b) => a - b);

const edges = [0, ...picked, 1];
const bands = edges.slice(0, -1).map((top, i) => ({
  top: +top.toFixed(5),
  height: +(edges[i + 1] - top).toFixed(5),
}));

writeFileSync(
  "scripts/transformation/bands.json",
  JSON.stringify({ bands }, null, 2) + "\n",
);

// The same data as a plain script, so the page needs no fetch and therefore
// works under file:// — which is how the renderer loads it.
writeFileSync(
  "scripts/transformation/bands.js",
  `/* generated by analyze.mjs — do not edit */\nwindow.BB_BANDS = ${JSON.stringify(bands)};\n`,
);

console.log(`${bands.length} bands from real page structure:`);
bands.forEach((b, i) =>
  console.log(
    `  ${String(i).padStart(2)}  top ${(b.top * 100).toFixed(1).padStart(5)}%   height ${(b.height * 100).toFixed(1).padStart(5)}%`,
  ),
);
