/* generated by analyze.mjs — do not edit */
window.BB_BANDS = [{"top":0,"height":0.15851},{"top":0.15851,"height":0.08415},{"top":0.24266,"height":0.25832},{"top":0.50098,"height":0.17613},{"top":0.6771,"height":0.11546},{"top":0.79256,"height":0.08415},{"top":0.87671,"height":0.12329}];
